set export

# When running in VS Code in a docker container, this is set to the home directory
# of the host machine. Since bind mount `/var/run/docker.sock` from the host to the
# VSCode docker container, we can kick off additional docker processes from VSCode,
# but any directories we mount need to know the host's home directory.
HOME_DIR := env_var_or_default('HOST_HOME', env_var('HOME'))

# Set to the distro you're running, like "bionic"
TEST_ENV_NAME := env_var('TEST_ENV_NAME')

CWD := justfile_directory()
TEST_DIR := env_var_or_default('TEST_DIR', "{{CWD}}")

# Run tests
test filter='':
    just run-tests '{{filter}}'

# Run general e2e tests
run-tests filter='': (update-tests)
    cd e2e && \
      TEST_DIR={{CWD}} \
      pyenv exec pytest {{filter}} -s .

# When running in a remote container, updates the /test code from the VS Code container workspace.
update-tests:
    #!/usr/bin/env bash
    set -euxo pipefail
    if [[ "${REMOTE_CONTAINERS}" == "true" ]]; then
        docker cp platform_lib_devcontainer:/workspaces/platform-lib/test/. /test/
    fi
