version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - errcheck
    - goheader
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    goheader:
      values:
        regexp:
          decade: '[0-9]'
          year: '[0-9]'
      template: Copyright (C) 20{{ decade }}{{ year }} by Posit Software, PBC
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - mock_.*\.go$
    rules:
      - linters:
          - staticcheck
        text: "QF1008|ST1001|ST1005|ST1019|SA1019|QF1003|ST1012|SA1029"
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/rstudio
        - rspm
  exclusions:
    generated: lax
    paths:
      - mock_.*\.go$
