version: '2.1'

services:
  lib:
    image: rstudio/platform-lib:lib-build
    build:
      context: bionic
      dockerfile: Dockerfile
    links:
      - postgres
      - minio
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    privileged: true
    volumes:
      - ..:/platform-lib
    environment:
      GO111MODULE: auto
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: miniokey
      AWS_DEFAULT_REGION: us-east-1
    working_dir: /platform-lib

  postgres:
    image: postgres:9.6
    ports:
      - "5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniokey
    command: minio server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
