version: '2.1'

services:
  lib:
    image: golang:1.22
    links:
      - postgres
      - minio
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    privileged: true
    volumes:
      - ..:/platform-lib
    environment:
      GO111MODULE: auto
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: miniokey
      AWS_DEFAULT_REGION: us-east-1
    working_dir: /platform-lib

  postgres:
    image: postgres:16
    ports:
      - "5432"
    environment:
      PGUSER: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniokey
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
