version: '3'

services:

    vscode:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        ports:
            - "5559"
        tty: true
        privileged: true
        volumes:
            - ~/:/userhome
            - ~/.aws:/root/.aws
            - /var/run/docker.sock:/var/run/docker.sock
